apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-client
  template:
    metadata:
      labels:
        app: server-client
    spec:
      containers:
      - name: server-client
        image: ajaff/podm-zeta:alpine
        ports:
        - containerPort: 8282
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: server-client-srv
spec:
  type: NodePort
  selector:
    app: server-client
  ports:
  - port: 8282
    targetPort: 8282
    nodePort: 31000
     
